@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
header Brooks and MacDonald
title Create Bill
actor server
participant "view : \nServerView" as view
participant "restaurant"
participant "controller : \nTableController" as controller
participant "controller2 : \nReceiptController" as Rcontroller
participant "tk.Frame : \nPrinter" as printer

server -> view ++ : Presses button to create the bill
view ->controller++: make_bills()
loop for seat in table
controller -> order: check if the seat has an order
controller -> controller--: add seat to list to display
end
create receipt

controller --> receipt: List of seats with orders

controller -> view: display receipt

view -> Rcontroller : displaybill()
Rcontroller -> receipt: getinfo()

loop for item in order

receipt -> order : to_print[item].append('item' - 'price')
end

receipt->printer : print(receipt)
'controller -> items++: mark_as_served()
'items->items--: item.state="SERVED"
'view->restaurant++: notify_view()
@enduml

Loop through the seats on the table
we need to display all the seats' orders
we need to create the buttons to indicate bill number

we need to add the seats that have orders to the drop down list


