@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
header Brooks and MacDonald
title Create Bill
actor server
participant "view : \nServerView" as view
participant "restaurant"
participant "controller : \nTableController" as controller
participant "controller2 : \nReceiptController" as Rcontroller
participant "tk.Frame : \nPrinter" as printer
participant "list[items]:\nledger" as ledger

server -> view ++ : Presses button to create the bill
view ->controller++: make_bills()
controller -> Rcontroller++: make_bills()

loop for order in table
Rcontroller -> Rcontroller: add seat to list to display
create receipt
Rcontroller --> receipt: List of seats with orders
end




controller -> view: display receipt

view -> Rcontroller : displaybill()
Rcontroller -> receipt: getinfo()

loop for item in order

receipt -> order : to_print[item].append('item' - 'price')
end

receipt->printer : print(receipt)





'controller -> items++: mark_as_served()
'items->items--: item.state="SERVED"
'view->restaurant++: notify_view()
@enduml
could make ledger instead of log.txt
-data easier to manipulate if in object instead

Loop through the seats on the table
we need to display all the seats' orders
we need to create the buttons to indicate bill number

we need to add the seats that have orders to the drop down list


